name: Schedule

on:
  schedule:
    - cron: '0 12 * * *'

jobs:
  format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install tox
        run: python -m pip install --no-cache-dir tox

      - name: Run ruff
        run: tox -e format

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install tox
        run: python -m pip install --no-cache-dir tox

      - name: Run ruff
        run: tox -e lint

  typecheck:
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install tox
        run: python -m pip install --no-cache-dir tox

      - name: Run mypy
        run: python -m tox -e typecheck

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - version: "3.12"
            toxenv: "py312"
          - version: "3.11"
            toxenv: "py311"
          - version: "3.10"
            toxenv: "py310"
          - version: "3.9"
            toxenv: "py39"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python.version }}

      - name: Install tox
        run: python -m pip install --no-cache-dir tox

      - name: Run pytest
        run: tox -e ${{ matrix.python.toxenv }}

  build_source_dist:
      name: Build source distribution
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-python@v5
          with:
            python-version: "3.12"

        - name: Install build
          run: python -m pip install build

        - name: Run build
          run: python -m build --sdist

        - uses: actions/upload-artifact@v4
          with:
            path: ./dist/*.tar.gz